name: dss
description: Stands for Dart StyleSheet.
version: 0.1.1
homepage: https://github.com/furrary/dss
author: Feu <furrary@gmail.com>

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dev_dependencies:
  build_runner:
  build_web_compilers:
  livereload:
